# Generated by Django 3.1.1 on 2020-09-10 00:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_help_need'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='help',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
