# Generated by Django 3.1.1 on 2020-09-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0004_auto_20200910_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='someoneneedshelp',
            name='number_of_people',
            field=models.CharField(max_length=10),
        ),
    ]
